-- Tabla de favoritos de usuario. Referencia polimórfica al producto por su
-- identificador externo (product_public_id, UUID) sin FK física: la integridad
-- se valida en la capa de aplicación (ADR-013). created_at la escribe la capa
-- de aplicación con Instant.now() al insertar; el DEFAULT queda como red de
-- seguridad para inserciones que no la fijen.
CREATE TABLE user_favorite_product (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            UUID        NOT NULL,
    product_type       VARCHAR(4)  NOT NULL,
    product_public_id  UUID        NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_favorite_product
        UNIQUE (user_id, product_type, product_public_id),
    CONSTRAINT ck_user_favorite_product_type
        CHECK (product_type IN ('BASE', 'USER'))
);
