-- Tabla de productos recientes de usuario. Referencia polimórfica al producto
-- por su identificador externo (product_public_id, UUID) sin FK física: la
-- integridad se valida en la capa de aplicación (ADR-013). last_used_at la
-- escribe la capa de aplicación con Instant.now() al marcar una interacción;
-- el DEFAULT queda como red de seguridad para inserciones que no la fijen.
CREATE TABLE user_recent_product (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            UUID        NOT NULL,
    product_type       VARCHAR(4)  NOT NULL,
    product_public_id  UUID        NOT NULL,
    last_used_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_recent_product
        UNIQUE (user_id, product_type, product_public_id),
    CONSTRAINT ck_user_recent_product_type
        CHECK (product_type IN ('BASE', 'USER'))
);
