-- GENERATED BY DEFAULT (no ALWAYS) para dejar la puerta abierta a un
-- futuro INSERT con id explícito (p. ej. migración de datos desde otro
-- sistema). El seed actual no lo usa; es robustez prospectiva, no un
-- requisito de V2.
CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(64) NOT NULL,
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_category_code UNIQUE (code)
);
