-- Tabla de productos base del catálogo, gestionada por el sistema. La FK a
-- category no lleva ON DELETE porque el borrado de una categoría con productos
-- activos es un caso de negocio que debe manejarse en capa de aplicación (sin
-- borrados silenciosos ni huérfanos en cascada).
CREATE TABLE base_product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(64)  NOT NULL,
    category_id  BIGINT       NOT NULL,
    default_unit VARCHAR(10)  NOT NULL,
    calories     INT,
    calories_per VARCHAR(10)  NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_base_product_code UNIQUE (code),
    CONSTRAINT fk_base_product_category
        FOREIGN KEY (category_id) REFERENCES category (id)
);
