-- Tabla raíz de listas de la compra. El identificador interno `id` es la clave
-- primaria subrogada (no expuesta); `public_id` es la identidad externa estable
-- (UUID v7), generada por la aplicación en runtime, sin DEFAULT ni trigger. El
-- índice sirve la consulta paginada de listas de un propietario, ordenada por
-- actividad (updated_at DESC) con desempate por id interno (id DESC).
CREATE TABLE list (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID         NOT NULL,
    owner_id   UUID         NOT NULL,
    name       VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_list_public_id UNIQUE (public_id)
);

CREATE INDEX idx_list_owner_updated
    ON list (owner_id, updated_at DESC, id DESC);
