-- Ítems de una lista de la compra. La referencia al producto es polimórfica por
-- (product_type, product_id), donde product_id es el public_id UUID del producto
-- (referencia cross-service, ADR-016); no hay FK física (database-per-service).
-- `display_name` es el snapshot congelado del nombre en el momento del alta.
-- La FK a `list` usa ON DELETE CASCADE: borrar la lista elimina sus ítems en el
-- motor. La unicidad (list_id, product_id, product_type) impide repetir el mismo
-- producto en la misma lista; su prefijo list_id sirve de índice para leer los
-- ítems de una lista.
CREATE TABLE list_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID         NOT NULL,
    list_id      BIGINT       NOT NULL,
    product_id   UUID         NOT NULL,
    product_type VARCHAR(4)   NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    purchased    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_list_item_public_id UNIQUE (public_id),
    CONSTRAINT fk_list_item_list
        FOREIGN KEY (list_id) REFERENCES list (id) ON DELETE CASCADE,
    CONSTRAINT ck_list_item_product_type
        CHECK (product_type IN ('BASE', 'USER')),
    CONSTRAINT uk_list_item_product
        UNIQUE (list_id, product_id, product_type)
);
