spring:
  application:
    name: list-service
  profiles:
    active: local
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  port: 8082
