-- Tabla de productos creados por el usuario. El texto es libre y monolingüe
-- (name/description como columnas directas, sin tabla de traducciones). La FK a
-- category no lleva ON DELETE (mismo criterio que base_product: el borrado de
-- una categoría con productos es un caso de negocio de capa de aplicación). La
-- FK a base_product usa ON DELETE SET NULL porque based_on_base_id es solo
-- trazabilidad histórica inmutable, no una referencia viva.
CREATE TABLE user_product (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id                UUID         NOT NULL,
    name                    VARCHAR(128) NOT NULL,
    description             TEXT,
    category_id             BIGINT,
    based_on_base_id        BIGINT,
    default_unit            VARCHAR(10)  NOT NULL,
    calories                INT,
    calories_per            VARCHAR(10)  NOT NULL,
    share_with_list_members BOOLEAN      NOT NULL DEFAULT FALSE,
    share_with_friends      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_product_category
        FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_user_product_base_product
        FOREIGN KEY (based_on_base_id) REFERENCES base_product (id) ON DELETE SET NULL
);
